### ISSUE TITLE
How to get api Key in dextools.io?

### ISSUE THREAD

**Issue by revived-midas** [joker-owner/dexscraper#2]

**Comment by revived-midas** [comment]
You can request in this url.
https://forms.gle/yviVwKYaqs81BMB77
But they aren't replying in time.

**Comment by joker-owner** [comment]
You can request in this url.
https://forms.gle/yviVwKYaqs81BMB77
But they aren't replying in time.

**Comment by revived-midas** [comment]
> You can request in this url. https://forms.gle/yviVwKYaqs81BMB77 But they aren't replying in time.

Thanks.
